name: Build and Push Container Image
on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'vscode-tunnel.sh'
      - '.github/workflows/pipeline.yml'
env:
  IMAGE_NAME: ${{ vars.DOCKER_IMAGE }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Push
        run: |
          docker build . -t $IMAGE_NAME:${{ github.sha }} -t $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest